"""add_conversation_state_table

Revision ID: 919b56b2fd8b
Revises: 5944687c4efd
Create Date: 2025-07-15 00:09:26.074856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919b56b2fd8b'
down_revision = '5944687c4efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('estado_actual', sa.String(length=50), nullable=True),
    sa.Column('datos_temporales', sa.Text(), nullable=True),
    sa.Column('ultimo_mensaje', sa.String(length=500), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_states_id'), 'conversation_states', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_states_numero_whatsapp'), 'conversation_states', ['numero_whatsapp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_states_numero_whatsapp'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_id'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ### 